search 4 datanucleus.properties...
NestedThrowablesStackTrace:
javax.jdo.JDOUserException: You have either specified for this PMF to use a \"persistence-unit\" of \"datanucleus.properties\" (yet this doesnt exist!) or you called JDOHelper.getPersistenceManagerFactory with \"datanucleus.properties\" as the name of a properties file (and this doesnt exist in the CLASSPATH)
	at org.datanucleus.jdo.JDOPersistenceManagerFactory.initialiseProperties(JDOPersistenceManagerFactory.java:377)
	at org.datanucleus.jdo.JDOPersistenceManagerFactory.<init>(JDOPersistenceManagerFactory.java:260)